//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILX.EF.DL
{
    using System;
    using System.Collections.Generic;
    
    		public  class TableDRepoEntity 
    		{
    		    public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> TableAID { get; set; }
    
        public virtual TableA TableA { get; set; }
        public virtual SPCoreUser SPCoreUser { get; set; }
    }
    		}
